line-length = 120
target-version = "py311"

[lint]
select = ["E", "F", "I", "N", "W", "UP", "DJ"]
ignore = ["DJ001"]

[lint.per-file-ignores]
"*/migrations/*" = ["ALL"]
"*/tests/*" = ["S101"]
"config/settings/local.py" = ["F403", "F405"]
"config/settings/production.py" = ["F403", "F405"]
"config/settings/test.py" = ["F403", "F405"]
"config/settings/base.py" = ["F405"]
